name: vaultwarden
on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Target architecture'
        type: choice
        options: [armv6l, armv7l, aarch64, x86_64, riscv64, all]
        default: all
        required: true
      dist:
        description: 'Target Debian version'
        type: choice
        options: [buster, bullseye, bookworm, trixie, all]
        default: all
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.arch }}-${{ github.event.inputs.dist }}
  cancel-in-progress: true
permissions: {}
defaults:
  run:
    shell: sh
    working-directory: /dev/shm
env:
  PY_COLORS: '1'
jobs:
  prep:
    outputs:
      arch: ${{ steps.arch.outputs.arch }}
      dist: ${{ steps.dist.outputs.dist }}
    # https://github.com/actions/runner-images
    runs-on: ubuntu-22.04
    steps:
    - id: arch
      run: |
        if [ '${{ github.event.inputs.arch }}' = 'all' ]
        then
          echo 'arch=["armv6l", "armv7l", "aarch64", "x86_64"]' >> "$GITHUB_OUTPUT"
        else
          echo 'arch=["${{ github.event.inputs.arch }}"]' >> "$GITHUB_OUTPUT"
        fi
    - id: dist
      run: |
        if [ '${{ github.event.inputs.dist }}' = 'all' ]
        then
          echo 'dist=["buster", "bullseye", "bookworm", "trixie"]' >> "$GITHUB_OUTPUT"
        else
          echo 'dist=["${{ github.event.inputs.dist }}"]' >> "$GITHUB_OUTPUT"
        fi
  build:
    needs: prep
    strategy:
      matrix:
        arch: ${{ fromJson(needs.prep.outputs.arch) }}
        dist: ${{ fromJson(needs.prep.outputs.dist) }}
        exclude:
        - { arch: riscv64, dist: buster }
        - { arch: riscv64, dist: bullseye }
        - { arch: riscv64, dist: bookworm }
      fail-fast: false
    name: "Build: ${{ matrix.arch }} - ${{ matrix.dist }}"
    runs-on: ubuntu-22.04
    steps:
    - name: Build
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=$GITHUB_REF_NAME; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/$GITHUB_REF_NAME/.build/software/vaultwarden/container_build.bash")" -- -a '${{ matrix.arch }}' -d '${{ matrix.dist }}'
    - name: Upload
      run: |
        # SSH server and client keys
        mkdir ~/.ssh
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519

        # Upload
        curl -T 'rootfs/vaultwarden_${{ matrix.arch }}.deb' --key ~/.ssh/id_ed25519 '${{ secrets.UPLOAD_URL }}${{ matrix.dist }}/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/${{ matrix.dist }}/testing/","https://dietpi.com/downloads/binaries/${{ matrix.dist }}/testing/vaultwarden_${{ matrix.arch }}.deb"]}'
