name: visionfive2
on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  build:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-24.04
    env:
      CROSS_COMPILE: 'aarch64-linux-gnu-'
      ARCH: 'arm64'
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        check-latest: true
    - name: Build init
      run: |
        { sudo apt-get -q update; sudo DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -qq install make gcc libc6-dev flex bison gcc-riscv64-linux-gnu bc libssl-dev; } &
        { curl -fO 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/snapshot/linux-6.11-rc2.tar.gz'; tar xf linux-6.11-rc2.tar.gz; rm llinux-6.11-rc2.tar.gz; } &
        wait
        curl -sSfo linux-6.11-rc2/arch/riscv64/configs/visionfive2_defconfig "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/$GITHUB_REF_NAME/.build/images/VisionFive2/visionfive2_defconfig" &
        rm -Rf linux-image-visionfive2
        mkdir -p linux-image-visionfive2/DEBIAN linux-image-visionfive2/boot/extlinux
        wait
    - name: Build Linux
      run: |
        cd linux-6.11-rc2
        make visionfive2_defconfig
        make -j$(nproc)
        cp arch/riscv64/boot/Image.gz ../linux-image-visionfive2/boot/vmlinuz
        mv arch/riscv64/boot/dts/rockchip/rk3566-quartz64-a.dtb ../linux-image-visionfive2/boot/
        make modules_install INSTALL_MOD_PATH='../linux-image-visionfive2'
        cd ..
        rm linux-image-visionfive2/lib/modules/*/build
    - name: Build package
      run: |
        version=$(mawk '/^VERSION =/{a=$3};/^PATCHLEVEL =/{b=$3};/^SUBLEVEL/{c=$3};END{print a"."b"."c}' linux-6.11-rc2/Makefile)
        rm -R linux-6.11-rc2
        curl -sSfO 'https://dietpi.com/downloads/binaries/linux-image-visionfive2.deb' &
        curl -sSfo linux-image-visionfive2/lib/firmware/brcm/brcmfmac43455-sdio.txt 'https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/brcm/brcmfmac43455-sdio.AW-CM256SM.txt' &
        wait
        cur_version=$(dpkg-deb -f linux-image-visionfive2.deb Version)
        rm linux-image-visionfive2.deb
        cur_suffix=${cur_version#*-dietpi}
        echo "Current package version is:  $cur_version"
        echo "New kernel version is:       $version"
        [ "$version-dietpi$cur_suffix" = "$cur_version" ] && version="$version-dietpi$((cur_suffix+1))" || version="$version-dietpi1"
        echo "New package version will be: $version"
        cat << '_EOF_' > linux-image-visionfive2/boot/extlinux/extlinux.conf
        label DietPi
        linux /boot/vmlinuz
        fdt /boot/rk3566-quartz64-a.dtb
        append root=/dev/mmcblk0p1 rootfstype=ext4 rootwait earlycon=uart8250,mmio32,0xfe660000 console=ttyS2,1500000n8 console=tty1 consoleblank=0 net.ifnames=0
        _EOF_
        echo '/boot/extlinux/extlinux.conf' > linux-image-visionfive2/DEBIAN/conffiles
        find linux-image-visionfive2 ! \( -path linux-image-visionfive2/DEBIAN -prune \) -type f -exec md5sum {} + | sed 's|linux-image-visionfive2/||' > linux-image-visionfive2/DEBIAN/md5sums
        cat << _EOF_ > linux-image-visionfive2/DEBIAN/control
        Package: linux-image-visionfive2
        Version: $version
        Architecture: arm64
        Maintainer: MichaIng <micha@dietpi.com>
        Date: $(date -u '+%a, %d %b %Y %T %z')
        Standards-Version: 4.6.2.0
        Installed-Size: $(du -sk 'linux-image-visionfive2' | mawk '{print $1}')
        Section: kernel
        Priority: optional
        Description: Linux kernel and U-Boot bootloader for Quartz64 Model A
        _EOF_
        sed --follow-symlinks -i "/^Installed-Size:/c\Installed-Size: $(du -sk 'linux-image-visionfive2' | mawk '{print $1}')" linux-image-visionfive2/DEBIAN/control
        sudo chown -R root:root linux-image-visionfive2
        dpkg-deb -b -Zxz -z9 -Sextreme linux-image-visionfive2
        sudo rm -R linux-image-visionfive2
    - name: Upload
      run: |
        [ -d ~/.ssh ] || mkdir ~/.ssh
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519
        curl -T "flinux-image-visionfive2.deb" --key ~/.ssh/id_ed25519 '${{ secrets.UPLOAD_URL }}all/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/testing/","https://dietpi.com/downloads/binaries/testing/linux-image-visionfive2.deb"]}'
